// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhPQs51I5yZoM6RsUUJHGjn8-q1fgji7s',
    appId: '1:791680752297:web:06ca7792392c373cb6e7b8',
    messagingSenderId: '791680752297',
    projectId: 'actvity-firebase',
    authDomain: 'actvity-firebase.firebaseapp.com',
    storageBucket: 'actvity-firebase.appspot.com',
    measurementId: 'G-1VZGNQW1X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGYjpEofkYIaq9e1h318QR9eQPUa43tls',
    appId: '1:791680752297:android:04ed408811c4740bb6e7b8',
    messagingSenderId: '791680752297',
    projectId: 'actvity-firebase',
    storageBucket: 'actvity-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBborZIEzYIohM2O7WBGQMwHTBymX1-JqE',
    appId: '1:791680752297:ios:b94bc1a1acc89137b6e7b8',
    messagingSenderId: '791680752297',
    projectId: 'actvity-firebase',
    storageBucket: 'actvity-firebase.appspot.com',
    iosClientId: '791680752297-gue9radj5k8aa87oph9rms76ut683h7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBborZIEzYIohM2O7WBGQMwHTBymX1-JqE',
    appId: '1:791680752297:ios:b94bc1a1acc89137b6e7b8',
    messagingSenderId: '791680752297',
    projectId: 'actvity-firebase',
    storageBucket: 'actvity-firebase.appspot.com',
    iosClientId: '791680752297-gue9radj5k8aa87oph9rms76ut683h7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
